instructor_companion.settings:
  type: config_object
  label: 'Instructor Companion settings'
  mapping:
    notification_email:
      type: email
      label: 'Instructor notification email'
    emergency_procedures_url:
      type: string
      label: 'Emergency procedures link'
    instructor_handbook_url:
      type: string
      label: 'Instructor handbook link'
    request_reimbursement_url:
      type: string
      label: 'Request reimbursement link'
    payment_status_url:
      type: string
      label: 'Payment status link'
    log_hours_url:
      type: string
      label: 'Log hours link'
